### ISSUE TITLE
Расширения при загрузке файлов

### ISSUE THREAD

**Issue by Premor** [Premor/some_site#1]
Сделано запоминание расширения при загрузке изображений, нужно сделать при добавлении альбома добавлять в encoding.json новый элемент

**Comment by GrandCatsWineGrapes** [comment]
Нужно отправлять расширения изображений в photos.jade и в photochange.jade

**Comment by Premor** [comment]
Осталось сделать эту хрень на админку (albumschange)

**Comment by Premor** [comment]
Все сделано
